POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "bell",
  "password": "09006543"
}


###
GET http://localhost:5003

###
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "nunu",
  "password": "12345678"
}

